services:
  mailing_provider:
    ports:
      - '1025:1025'
    command:
      - --log-mail-contents

  oauth_provider:
    ports:
      - '9000:9000'
    command:
      - start-dev
      - --import-realm
    environment:
      KC_HTTP_MANAGEMENT_PORT: 9000
      KC_HTTP_MANAGEMENT_RELATIVE_PATH: '/'

  sqldb_provider:
    ports:
      - '5432:5432'
